name: Pipeline development and production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: url
    steps:
      - name: Echo the trigger name
        run: echo "The trigger name is ${{ github.event_name }}"
